name: Check

# Trigger
on:
  workflow_dispatch:

# Define Jobs
jobs:
  # job - build
  build:
    # Runner
    runs-on: ubuntu-latest
    
    # List Steps
    steps:
      - uses: actions/checkout@v4

      - name: Run 
        run: echo Hello, World

      - name: Run multiple line
        run: |
          echo "First output1"
          echo "Second output2"