name: Check

# Trigger
on:
  workflow_dispatch:

# Define Jobs
jobs:
  # job - build
  build:
    # Runner
    runs-on: ubuntu-latest
    
    # List Steps
    steps:
      - uses: actions/checkout@v4

      - name: Run 
        run: echo "prod_account_id=${{vars.ACCOUNT_MAPPING}}"

      - name: Run 12
        run: echo "prod_account_id=${{env.ACCOUNT_MAPPING}}"